[package]
edition = "2021"
name = "pop-drink"
version = "0.1.0"

[dependencies]
drink = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
ink_sandbox = { workspace = true, default-features = false }
pop-runtime-devnet = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }

[features]
default = [
	"std",
]
std = [
	"drink/std",
	"frame-support/std",
	"ink_sandbox/std",
	"pop-runtime-devnet/drink",
	"pop-runtime-devnet/std",
	"sp-io/std",
]
