[package]
edition = "2021"
name = "pop-drink"
version = "0.1.0"

[dependencies]
drink.workspace = true
frame-support-procedural.workspace = true
frame-support.workspace = true
ink_sandbox.workspace = true
pop-runtime-devnet.workspace = true
pallet-contracts.workspace = true
frame-system.workspace = true
frame-support.workspace = true
sp-io.workspace = true
scale.workspace = true
pop-api.workspace = true
