[package]
name = "pop-drink"
version = "0.1.0"
edition = "2021"

[dependencies]
drink.workspace = true
ink_sandbox.workspace = true
pop-runtime-devnet.workspace = true
pallet-contracts.workspace = true
frame-system.workspace = true
frame-support.workspace = true
sp-io.workspace = true
scale.workspace = true
pop-api.workspace = true

[features]
default = [
    "std",
]
std = [
    "pop-runtime-devnet/std",
    "pop-api/std",
    "scale/std",
    "frame-support/std",
    "sp-io/std",
]
